# Generated by Django 4.1.7 on 2023-04-30 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='AdditionsToTheProfile',
        ),
    ]
