# Generated by Django 4.1.7 on 2023-03-22 11:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=150, verbose_name='Учетная запись игры')),
                ('store_region', models.CharField(max_length=50, verbose_name='Регион магазина')),
                ('logo_region', models.ImageField(upload_to='', verbose_name='Логотип региона')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
            ],
            options={
                'verbose_name': 'Учетная запись',
                'verbose_name_plural': 'Учетные записи',
                'ordering': ('-creation_date',),
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50, verbose_name='Платформа')),
                ('type_activation', models.CharField(max_length=10, verbose_name='Тип активации')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='games.account', verbose_name='Учетная запись')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Владелец',
                'verbose_name_plural': 'Владельцы',
                'ordering': ('-creation_date',),
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название игры')),
                ('logo', models.ImageField(blank=True, upload_to='static/posts/', verbose_name='Логотип игры')),
                ('description', models.TextField(verbose_name='Описание игры')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг игры')),
                ('release_date', models.CharField(max_length=20, verbose_name='Дата выхода')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='games.owner', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ('-creation_date',),
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('organizer', 'login'), name='unique_login'),
        ),
    ]
