# Generated by Django 4.1.7 on 2023-04-22 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_owner_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='is_published',
        ),
    ]
