# Generated by Django 4.1.7 on 2023-04-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_account_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='logo_region',
            field=models.ImageField(blank=True, upload_to='static/logo_region/%Y/%m/%d/', verbose_name='Логотип региона'),
        ),
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.ImageField(blank=True, upload_to='static/logo/%Y/%m/%d/', verbose_name='Логотип игры'),
        ),
    ]
