# Generated by Django 4.1.7 on 2023-04-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_account_logo_region_alter_game_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название игры'),
        ),
    ]
