# Generated by Django 4.1.7 on 2023-04-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='login',
            field=models.CharField(max_length=255, verbose_name='Учетная запись игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.CharField(max_length=50, verbose_name='Дата выхода'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='platform',
            field=models.CharField(max_length=100, verbose_name='Платформа'),
        ),
    ]
