# Generated by Django 4.1.7 on 2023-04-21 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_review', to=settings.AUTH_USER_MODEL, verbose_name='Автор отзыва'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL, verbose_name='Объект отзыва'),
        ),
        migrations.AddField(
            model_name='postsale',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='games.account', verbose_name='Аккаунт'),
        ),
        migrations.AddField(
            model_name='postsale',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AddField(
            model_name='favoritepost',
            name='post_sale',
            field=models.ManyToManyField(related_name='favorite_post', to='posts.postsale', verbose_name='Избранный пост'),
        ),
        migrations.AddField(
            model_name='favoritepost',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_post', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
