# Generated by Django 4.1.7 on 2023-04-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_favoritepost_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.CharField(choices=[('PV', 'Положительный'), ('NT', 'Нейтральный'), ('NV', 'Отрицательный')], default='PV', max_length=2, verbose_name='оценка'),
        ),
    ]
