# Generated by Django 4.1.7 on 2023-04-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_review_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsale',
            name='type_payment',
            field=models.CharField(max_length=255, verbose_name='Вариант оплаты'),
        ),
    ]
