# Generated by Django 4.1.7 on 2023-04-22 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_postsale_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsale',
            name='is_published',
        ),
    ]
