# Generated by Django 4.1.7 on 2023-04-26 20:53

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_message_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Сообщение'),
        ),
    ]
